from: ${PROFZONE_DOCKER_REGISTRY}/profzone/golang:runtime
image: ${PROFZONE_DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
workdir: /go/bin
env:
  GOENV: DEV
  S_CLIENTID_HOST: service-id.profzone.rancher.internal
  S_CLIENTID_PORT: "80"
  S_LOG_FORMAT: json
  S_MASTERDB_HOST: configuration.db-routers.rancher.internal
  S_MASTERDB_PORT: "3306"
  S_SERVER_PORT: "80"
  S_SERVER_WITHCORS: "false"
  S_SLAVEDB_HOST: configuration-readonly.db-routers.rancher.internal
  S_SLAVEDB_PORT: "3306"
add:
  ./config: ./config
  ./profzone.yml: ./
  ./service-configurations: ./
  ./swagger.json: ./
expose:
- "80"
cmd:
- ./service-configurations
- -c=false
